spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mybatis_test?serverTimezone=UTC&useUnicode=true@characterEncoding=utf-8
    username: laowang
    password: laowang_123456
    driver-class-name: com.mysql.cj.jdbc.Driver